name: nutri_life
description: Aplicativo Nutri Life
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  firebase_auth: any
  shared_preferences: ^2.2.2  # 🔐 Motor de Login Automático
  image_picker: ^1.0.4
  http: ^1.2.0
  mobile_scanner: ^5.0.0
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # 🚀 Gerador Automático de Ícones Oficial

# 🎨 Configuração da Logo Oficial do Nutri Life
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "image/icon.png"

flutter:
  uses-material-design: true
