name: Compilar Nutri Life (Android APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Gerar Motor Android Básico
        run: |
          flutter create --platforms android --project-name nutri_life temp_app
          cp -r temp_app/android ./android
          rm -rf temp_app
          
          # Mantemos apenas o ajuste de versão mínima para o Firestore rodar
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle

      - name: Instalar dependências (pub get)
        run: flutter pub get

      - name: Construir o APK (Release)
        run: flutter build apk --release

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: NutriLife-APK
          path: build/app/outputs/flutter-apk/app-release.apk
