name: Compilar Nutri Life (Android APK)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # ==========================================
      # TRUQUE MÁGICO 2.1: CONFIGURADOR FIREBASE ATUALIZADO
      # ==========================================
      - name: Configurar Motor Android e Firebase
        run: |
          flutter create --platforms android --project-name nutri_life temp_app
          cp -r temp_app/android ./android
          rm -rf temp_app
          
          # Move a chave do Firebase da raiz para o cofre do Android
          if [ -f "google-services.json" ]; then
            echo "✅ Chave do Firebase encontrada! Movendo para o app..."
            mv google-services.json android/app/
          else
            echo "⚠️ AVISO: google-services.json não encontrado na raiz!"
          fi
          
          # Ajustar a versão mínima exigida pelo banco de dados (API 21)
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          
          # Injetar o plugin do Google Services no NOVO arquivo do Flutter (settings.gradle)
          sed -i 's/id "com.android.application" version/id "com.google.gms.google-services" version "4.4.1" apply false\n    id "com.android.application" version/g' android/settings.gradle
          
          # Aplicar o plugin dentro do aplicativo
          sed -i 's/id "com.android.application"/id "com.android.application"\n    id "com.google.gms.google-services"/g' android/app/build.gradle

      - name: Instalar dependências (pub get)
        run: flutter pub get

      - name: Construir o APK (Release)
        run: flutter build apk --release

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: NutriLife-APK
          path: build/app/outputs/flutter-apk/app-release.apk
