name: Compilar App do Paciente (PWA)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Gerar Motor Web Básico
        run: |
          flutter create --platforms web .

      - name: Instalar dependências (pub get)
        run: flutter pub get

      - name: Construir o PWA (Release)
        # O comando abaixo compila o app e garante a estratégia offline-first do PWA
        run: flutter build web --release --pwa-strategy=offline-first

      - name: Disponibilizar Site para Download
        uses: actions/upload-artifact@v4
        with:
          name: app-paciente-web
          path: build/web/
