name: Compilar APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Gerar Motor Android Básico
        run: |
          flutter create --platforms android --project-name nutri_life temp_app
          rm -rf android
          mv temp_app/android .
          rm -rf temp_app
          echo "flutter.minSdkVersion=26" >> android/local.properties
          
          if [ -f "android/app/build.gradle.kts" ]; then
            echo 'android { compileOptions { isCoreLibraryDesugaringEnabled = true } }' >> android/app/build.gradle.kts
            echo 'dependencies { "coreLibraryDesugaring"("com.android.tools:desugar_jdk_libs:2.0.3") }' >> android/app/build.gradle.kts
          elif [ -f "android/app/build.gradle" ]; then
            echo 'android { compileOptions { coreLibraryDesugaringEnabled true } }' >> android/app/build.gradle
            echo "dependencies { coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3' }" >> android/app/build.gradle
          fi

      - name: Injetar Permissões e Nome do App
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          
          # Altera o nome do aplicativo para "Nutri Life"
          sed -i 's/android:label="nutri_life"/android:label="Nutri Life"/g' $MANIFEST
          
          # MÁGICA CORRIGIDA: Injeta as permissões ANTES da tag <application> para não quebrar o XML
          PERMS='<uses-permission android:name="android.permission.INTERNET"/>\n    <uses-permission android:name="android.permission.CAMERA"/>\n    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>\n    <uses-permission android:name="android.permission.VIBRATE"/>\n    <uses-permission android:name="android.permission.WAKE_LOCK"/>\n    <uses-permission android:name="android.permission.USE_EXACT_ALARM"/>\n    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM"/>\n    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>\n    <application'
          
          sed -i "s/<application/$PERMS/g" $MANIFEST

      - name: Instalar dependências (pub get)
        run: flutter pub get

      - name: Gerar Ícones Oficiais
        run: flutter pub run flutter_launcher_icons

      - name: Construir o APK (Release)
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3"
          flutter build apk --release

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
